export struct DealerData {
  first_name: string,
  middle_name: string,
  last_name: string,
  country_code: string,
  phone_num: string,
  image: image,
}

export struct ProductData {
  brand_name: string,
  product_name: string,
  item_name: string,
  pack_name: string,
  image: image,
}

export struct DealerPricePair {
  dealer: DealerData,
  price: int,
}

export struct ProductDealerConnection {
  product: ProductData,
  dealer_price_pair: DealerPricePair,
}

export struct ProductDealersConnection {
  product: ProductData,
  dealer_price_pairs: [DealerPricePair],
}

export struct ProductSelectionInput {
  best_results: [ProductData],
  recent_results: [ProductData],
}

export struct ComparisonTableInput {
  product_dealers_connection: ProductDealersConnection,
}

export struct ProductSearchInput {
  results: [ProductData],
}

export struct DealerSearchInput {
  results: [DealerData],
}

export struct DataFeedInput {
  product_dealers_connection: ProductDealersConnection,
  index: int,
}

export enum Mode {
  ComparisonProductSelection,
  ComparisonTable,
  ProductSearch,
  ProductAdd,
  DealerSearch,
  DealerAdd,
  DataFeedSelection,
  DataFeedProcedure,
}
