// Data Structures
import { DesignData } from "design_data.slint";
import { Colors } from "colors.slint";
import { DealerData, ProductData, ProductDealersConnection, 
         ProductSelectionInput, ComparisonTableInput,
         ProductSearchInput, DealerSearchInput, DataFeedInput,
         Mode } from "data_structures.slint";

// Layout Abstractions
import { Header } from "header.slint";
import { SideBar } from "sidebar.slint";
import { ComparisonLayout } from "comparison.slint";
import { ProductPageLayout } from "product_page.slint";
import { DealerPageLayout } from "dealer_page.slint";
import { DataFeedLayout } from "data_feed.slint";

export struct Data {
  product_selection_input: ProductSelectionInput,
  comparison_table_input: ComparisonTableInput,
  product_search_input: ProductSearchInput,
  dealer_search_input: DealerSearchInput,
  data_feed_input: DataFeedInput,
}

export component MainWindow inherits Window {
  width: 16px * self.design_data.win_scale;
  height: 9px * self.design_data.win_scale;
  background: Colors.vd_gray;

  // Design info
  property<DesignData> design_data: {
    win-scale: 100,
    padding: 40px,
    gutter: 16px,
    columns: 12
  };

  // Data input - common
  property<[string]> pages_name: [
    "Comparison Table",
    "Products",
    "Dealers",
    "Data Feed"
  ];
  property<[Mode]> pages_initial_mode: [
    Mode.ComparisonProductSelection,
    Mode.ProductSearch,
    Mode.DealerSearch,
    Mode.DataFeedSelection,
  ];
  in-out property<int> selected_page: 0;
  in-out property<bool> sidebar_activated: true;

  in-out property<Mode> mode: Mode.ComparisonProductSelection;
  in-out property<Data> input_data;

  // Callbacks
  callback mode_changed(Mode);
  callback search_text_changed(string, Mode);
  callback add_product(ProductData);
  callback add_dealer(DealerData);
  callback product_selected(ProductData, Mode);
  callback price_changed(ProductData, DealerData, string);
  callback increment_data_feed();

  VerticalLayout {
    alignment: start;
    Header {
      header_title: pages_name[selected_page];
      des_data: design_data;
      onHamburgerMenu => {
        sidebar_activated = !sidebar_activated;
      }
    }

    HorizontalLayout {
      if sidebar_activated : SideBar {
        des_data: design_data;
        pages: pages_name;
        selected_page: selected_page;
        clicked(idx) => {
          selected_page = idx;
          mode = pages_initial_mode[idx];
          mode_changed(mode);
        }
      }

      if selected_page == 0 : ComparisonLayout {
        des_data: design_data;
        product_selection_input: input_data.product_selection_input;
        table_input: input_data.comparison_table_input;
        mode: mode;

        product_selected(pr) => {
          mode = Mode.ComparisonTable;
          mode_changed(mode);
          product_selected(pr, mode);
        }
        search_text_changed(new_text) => {
          root.search_text_changed(new_text, mode);
        }
      }
      if selected_page == 1 : ProductPageLayout {
        des_data: design_data;
        sidebar_activated: sidebar_activated;
        product_search_input: input_data.product_search_input;
        mode: mode;

        add_product_mode => {
          mode = Mode.ProductAdd;
          mode_changed(mode);
        }
        cancel_add_product_mode => {
          mode = Mode.ProductSearch;
          mode_changed(mode);
        }
        add_the_product(data) => {
          add_product(data);
          mode = Mode.ProductSearch;
          mode_changed(mode);
        }
        search_text_changed(new_text) => {
          root.search_text_changed(new_text, mode);
        }
      }
      if selected_page == 2 : DealerPageLayout {
        des_data: design_data;
        sidebar_activated: sidebar_activated;
        dealer_search_input: input_data.dealer_search_input;
        mode: mode;

        dealer_add_mode => {
          mode = Mode.DealerAdd;
          mode_changed(mode);
        }
        cancel_dealer_add_mode => {
          mode = Mode.DealerSearch;
          mode_changed(mode);
        }
        add_the_dealer(data) => {
          add_dealer(data);
          mode = Mode.DealerSearch;
          mode_changed(mode);
        }
        search_text_changed(new_text) => {
          root.search_text_changed(new_text, mode);
        }
      }
      if selected_page == 3 : DataFeedLayout {
        des_data: design_data;
        product_selection_input: input_data.product_selection_input;
        data_feed_input: input_data.data_feed_input;
        mode: mode;

        product_selected(pr) => {
          mode = Mode.DataFeedProcedure;
          mode_changed(mode);
          product_selected(pr, mode);
          if input_data.data_feed_input.product_dealers_connection.dealer_price_pairs.length == 0 {
            mode = Mode.DataFeedSelection;
            mode_changed(mode);
          }
        }
        search_text_changed(new_text) => {
          root.search_text_changed(new_text, mode);
        }

        price_changed(product, dealer, price) => {
          root.price_changed(product, dealer, price);
        }

        feed_completed => {
          mode = Mode.DataFeedSelection;
          mode_changed(mode);
        }

        increment_data_feed => {
          root.increment_data_feed();
        }
      }
    }
  }
}
