export component H1Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 2.98625rem;
  }
}
export component H2Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 2.488rem;
  }
}
export component H3Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 2.074rem;
  }
}
export component H4Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 1.728rem;
  }
}
export component H5Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 1.44rem;
  }
}
export component H6Text {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 1.2rem;
  }
}
export component ParagraphText {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 1rem;
  }
}
export component CaptionText {
  in property<string> in_text: "text is missing";
  in property<color> in_color: white;

  Text {
    text: in_text;
    color: in_color;
    font-family: "Space Grotesk";
    font_size: 0.833rem;
  }
}
